name: hybrid_list_tile
description: HybridListTile widget allows creating customized ListTiles with various properties like padding, colors, icons, titles, subtitles, and more.
version: 1.1.0
homepage: https://rudo.es/
repository: https://github.com/rudoapps/hybrid-list-tile.git
issue_tracker: https://github.com/rudoapps/hybrid-list-tile/issues
topics:
 - listtile

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # Material
  uses-material-design: true